Ajout de la verification du breacking bug et un echec de test

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -28,3 +28,12 @@ jobs:
         run: npm run lint
       - name: Test
         run: npm test
+      - name: Check breaking bug
+        run: |
+          # Exécutez ESLint avec votre fichier de configuration
+          npx eslint --config ../../.eslintrc.js --ignore-path .gitignore .
+          # Fail the workflow if ESLint finds issues
+          if [ $? -ne 0 ]; then
+          echo "Found breaking bugs. PR cannot be merged."
+          exit 1
+          fi
